### ISSUE TITLE
Support text buttons on mobile modal

### ISSUE THREAD

**Issue by stephenreay** [keaukraine/bootstrap-fs-modal#1]
Even in the simple demo app, it wasn't obvious to me what the "tick" button in the top right would do. I think there should at the very least be an option (jf not a default) to keep the original button's text.

UX studies of website users have consistently shown that clear, text labels (e.g. "Menu" rather than a 'Hamburger' icon) are easier to comprehend.

I actually have a use for this on a client project, if I get time this week I'll make a PR with the above change as an option.

**Comment by keaukraine** [comment]
Thank you for helpful suggestion, will implement this. I'll add buttons without special data attribute for icon as text buttons.

**Comment by keaukraine** [comment]
I've implemented text buttons, trying to make it flexible and easy to use for both icon and text buttons.

Now plugin runs through all buttons in footer except the ones with `data-dismiss="modal"` attribute (this is close button, added separately), and adds them with or without icon depending on presence of `data-glyphicon` attribute. If this attribute is not set, it will add text button. It will try to apply short text (in demo, "Reload" instead of "Reload Data") by looking for short button text in `data-mobile-text` attribute and falling back to button text if attribute is not set.

Please feel free improving this implementation with PRs.

**Comment by stephenreay** [comment]
Wow, that was quick. That's sounds like a pretty decent approach, and sounds like basically what I would have done anyway. Thanks!

**Comment by keaukraine** [comment]
Can I close issue?
